# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nessus_ingest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nessus_ingest.proto',
  package='projectprismatica.official.nessus',
  syntax='proto3',
  serialized_pb=_b('\n\x13nessus_ingest.proto\x12!projectprismatica.official.nessus\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2z\n\x0cNessusIngest\x12j\n\x06Nessus\x12/.projectprismatica.official.nessus.HelloRequest\x1a-.projectprismatica.official.nessus.HelloReply\"\x00\x62\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='projectprismatica.official.nessus.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='projectprismatica.official.nessus.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='projectprismatica.official.nessus.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='projectprismatica.official.nessus.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'nessus_ingest_pb2'
  # @@protoc_insertion_point(class_scope:projectprismatica.official.nessus.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'nessus_ingest_pb2'
  # @@protoc_insertion_point(class_scope:projectprismatica.official.nessus.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)



_NESSUSINGEST = _descriptor.ServiceDescriptor(
  name='NessusIngest',
  full_name='projectprismatica.official.nessus.NessusIngest',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=119,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='Nessus',
    full_name='projectprismatica.official.nessus.NessusIngest.Nessus',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NESSUSINGEST)

DESCRIPTOR.services_by_name['NessusIngest'] = _NESSUSINGEST

# @@protoc_insertion_point(module_scope)
