// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prismatica_integration_nessus.proto

/*
Package prismatica_integration_nessus is a generated protocol buffer package.

It is generated from these files:
	prismatica_integration_nessus.proto

It has these top-level messages:
	SubmissionRequest
	SubmissionResult
*/
package prismatica_integration_nessus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubmissionResult_ResultStatus int32

const (
	SubmissionResult_UNKNOWN         SubmissionResult_ResultStatus = 0
	SubmissionResult_SUCCESS         SubmissionResult_ResultStatus = 1
	SubmissionResult_UNKNOWN_FAILURE SubmissionResult_ResultStatus = 2
)

var SubmissionResult_ResultStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "UNKNOWN_FAILURE",
}
var SubmissionResult_ResultStatus_value = map[string]int32{
	"UNKNOWN":         0,
	"SUCCESS":         1,
	"UNKNOWN_FAILURE": 2,
}

func (x SubmissionResult_ResultStatus) String() string {
	return proto.EnumName(SubmissionResult_ResultStatus_name, int32(x))
}
func (SubmissionResult_ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type SubmissionRequest struct {
	// The raw XML report from nessus
	XmlReport string `protobuf:"bytes,1,opt,name=xmlReport" json:"xmlReport,omitempty"`
}

func (m *SubmissionRequest) Reset()                    { *m = SubmissionRequest{} }
func (m *SubmissionRequest) String() string            { return proto.CompactTextString(m) }
func (*SubmissionRequest) ProtoMessage()               {}
func (*SubmissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubmissionRequest) GetXmlReport() string {
	if m != nil {
		return m.XmlReport
	}
	return ""
}

type SubmissionResult struct {
	Status SubmissionResult_ResultStatus `protobuf:"varint,1,opt,name=status,enum=prismatica_integration_nessus.SubmissionResult_ResultStatus" json:"status,omitempty"`
	Hint   string                        `protobuf:"bytes,2,opt,name=hint" json:"hint,omitempty"`
}

func (m *SubmissionResult) Reset()                    { *m = SubmissionResult{} }
func (m *SubmissionResult) String() string            { return proto.CompactTextString(m) }
func (*SubmissionResult) ProtoMessage()               {}
func (*SubmissionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubmissionResult) GetStatus() SubmissionResult_ResultStatus {
	if m != nil {
		return m.Status
	}
	return SubmissionResult_UNKNOWN
}

func (m *SubmissionResult) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func init() {
	proto.RegisterType((*SubmissionRequest)(nil), "prismatica_integration_nessus.SubmissionRequest")
	proto.RegisterType((*SubmissionResult)(nil), "prismatica_integration_nessus.SubmissionResult")
	proto.RegisterEnum("prismatica_integration_nessus.SubmissionResult_ResultStatus", SubmissionResult_ResultStatus_name, SubmissionResult_ResultStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PrismaticaIntegrationNessus service

type PrismaticaIntegrationNessusClient interface {
	SubmitReport(ctx context.Context, in *SubmissionRequest, opts ...grpc.CallOption) (*SubmissionResult, error)
}

type prismaticaIntegrationNessusClient struct {
	cc *grpc.ClientConn
}

func NewPrismaticaIntegrationNessusClient(cc *grpc.ClientConn) PrismaticaIntegrationNessusClient {
	return &prismaticaIntegrationNessusClient{cc}
}

func (c *prismaticaIntegrationNessusClient) SubmitReport(ctx context.Context, in *SubmissionRequest, opts ...grpc.CallOption) (*SubmissionResult, error) {
	out := new(SubmissionResult)
	err := grpc.Invoke(ctx, "/prismatica_integration_nessus.PrismaticaIntegrationNessus/SubmitReport", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrismaticaIntegrationNessus service

type PrismaticaIntegrationNessusServer interface {
	SubmitReport(context.Context, *SubmissionRequest) (*SubmissionResult, error)
}

func RegisterPrismaticaIntegrationNessusServer(s *grpc.Server, srv PrismaticaIntegrationNessusServer) {
	s.RegisterService(&_PrismaticaIntegrationNessus_serviceDesc, srv)
}

func _PrismaticaIntegrationNessus_SubmitReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismaticaIntegrationNessusServer).SubmitReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prismatica_integration_nessus.PrismaticaIntegrationNessus/SubmitReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismaticaIntegrationNessusServer).SubmitReport(ctx, req.(*SubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrismaticaIntegrationNessus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prismatica_integration_nessus.PrismaticaIntegrationNessus",
	HandlerType: (*PrismaticaIntegrationNessusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitReport",
			Handler:    _PrismaticaIntegrationNessus_SubmitReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prismatica_integration_nessus.proto",
}

func init() { proto.RegisterFile("prismatica_integration_nessus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0xca, 0x2c,
	0xce, 0x4d, 0x2c, 0xc9, 0x4c, 0x4e, 0x8c, 0xcf, 0xcc, 0x2b, 0x49, 0x4d, 0x2f, 0x4a, 0x2c, 0xc9,
	0xcc, 0xcf, 0x8b, 0xcf, 0x4b, 0x2d, 0x2e, 0x2e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x92, 0xc5, 0xab, 0x48, 0xc9, 0x90, 0x4b, 0x30, 0xb8, 0x34, 0x29, 0x37, 0xb3, 0xb8, 0x38, 0x33,
	0x3f, 0x2f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x86, 0x8b, 0xb3, 0x22, 0x37, 0x27,
	0x28, 0xb5, 0x20, 0xbf, 0xa8, 0x44, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x21, 0xa0, 0xb4,
	0x9b, 0x91, 0x4b, 0x00, 0x59, 0x4f, 0x71, 0x69, 0x4e, 0x89, 0x50, 0x08, 0x17, 0x5b, 0x71, 0x49,
	0x62, 0x49, 0x69, 0x31, 0x58, 0x3d, 0x9f, 0x91, 0x8d, 0x1e, 0x7e, 0xc7, 0xa1, 0x1b, 0xa0, 0x07,
	0xa1, 0x82, 0xc1, 0x66, 0x04, 0x41, 0xcd, 0x12, 0x12, 0xe2, 0x62, 0xc9, 0xc8, 0xcc, 0x2b, 0x91,
	0x60, 0x02, 0xbb, 0x01, 0xcc, 0x56, 0xb2, 0xe5, 0xe2, 0x41, 0x56, 0x2b, 0xc4, 0xcd, 0xc5, 0x1e,
	0xea, 0xe7, 0xed, 0xe7, 0x1f, 0xee, 0x27, 0xc0, 0x00, 0xe2, 0x04, 0x87, 0x3a, 0x3b, 0xbb, 0x06,
	0x07, 0x0b, 0x30, 0x0a, 0x09, 0x73, 0xf1, 0x43, 0x65, 0xe2, 0xdd, 0x1c, 0x3d, 0x7d, 0x42, 0x83,
	0x5c, 0x05, 0x98, 0x8c, 0x26, 0x31, 0x72, 0x49, 0x07, 0xc0, 0x9d, 0xe6, 0x89, 0x70, 0x99, 0x1f,
	0xd8, 0x61, 0x42, 0xc5, 0x5c, 0x3c, 0x60, 0xb7, 0x95, 0x40, 0x7c, 0x2b, 0x64, 0x40, 0x82, 0x47,
	0xc0, 0xa1, 0x27, 0xa5, 0x4f, 0xa2, 0xd7, 0x95, 0x18, 0x9c, 0x6c, 0xa3, 0xac, 0xd3, 0x33, 0x4b,
	0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x03, 0x8a, 0xf2, 0xb3, 0x52, 0x93, 0x4b, 0x74,
	0x11, 0xce, 0xd4, 0xc7, 0x6b, 0x62, 0x12, 0x1b, 0x38, 0xaa, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x54, 0x7c, 0x54, 0xda, 0x11, 0x02, 0x00, 0x00,
}
